# Custom keymapping
map f1 new_tab_with_cwd
map f2 close_tab
mouse_map ctrl+left click ungrabbed mouse_handle_click link


# Clipboard
copy_on_select     yes
clipboard_max_size 512

disable_ligatures  never
symbol_map U+2580-U+259F Noto Sans Mono

# Text selection
selection_foreground #000000
selection_background #9bbff1


# Terminal geometry size
initial_window_width  115c
initial_window_height 29c


# URL
clear_selection_on_clipboard_loss no
detect_urls                       yes
url_color                         #64adc5
url_style                         dotted
allow_hyperlinks                  yes


# Colors
# black
color0  #000000
color8  #555753

# red
color1  #ff2424
color9  #ff2626

# green
color2  #69ff47
color10 #52de33

# yellow
color11 #e6ce0e
color3  #fcd528

# blue
color12 #2e92ff
color4  #3b96ff

# magenta
color13 #e558e8
color5  #e438ff

# cyan
color6  #4df8fa
color14 #4fe0e0

# white
color7  #d3d7cf
color15 #eeeeec


# Fonts
font_family FiraCode Nerd Font
font_size 10


# Display
foreground            #d9d9d9
background_opacity    0.85
background            #131517
window_padding_width  12
remember_window_size  yes
initial_window_width  150c
initial_window_height 50c


# Text cursor
cursor_shape               beam
cursor_blink_interval      0.4
cursor_stop_blinking_after 6.0


# Scroll lines
scrollback_lines        4000
wheel_scroll_multiplier 5.0


# Performance
repaint_delay    10
input_delay      4
sync_to_monitor  yes


# Window layout
active_tab_foreground    #fff
active_tab_background    #a946f8
inactive_tab_foreground  #0f0f0f
inactive_tab_background  #8d8d8d
tab_bar_style            separator
tab_powerline_style      slanted
active_tab_font_style    bold
inactive_tab_font_style  normal
tab_bar_edge             bottom
tab_separator            " | "
inactive_border_color    #cccccc
window_border_width      3
draw_minimal_borders     yes
active_border_color      #89b8fa
inactive_border_color    #3e3d3d


# Background image
#background_image        <image-absolute-path>
#background_image_layout scaled
#background_tint         0.96
