[general]
color = "#3b82f6"
interval = 150
blink = true
bold = false

[position]
horizontal = "center"
vertical = "center"

[date]
fmt = "%a, %d %b, %Y"
use_12h = true
utc = false
hide_seconds = true
