# Hyprland

$active_border = rgba(3b82f6ff)
$inactive_border = rgba(1f2937aa)
$shadow = rgba(1a1a1aee)

# Hyprlock

$image_border = rgba(255, 255, 255, 0.44)
$input_field_out_border = rgba(255, 255, 255, 0.08)
$input_field_in_border = rgba(255, 255, 255, 0.03)
$input_field_font = rgba(220, 220, 220, 1.0)
