# Hyprlock

$image_border = rgba(255, 255, 255, 0.55)
$input_field_out_border = rgba(255, 255, 255, 0.08)
$input_field_in_border = rgba(130, 147, 176, 0.07)
$input_field_font = rgba(188, 204, 215, 1.0)
$input_field_check_color = rgba(113, 156, 228, 0.8);
