background {
    monitor =
    path = /home/xingyun/Pictures/wallpapers/re8.jpg
    blur_passes = 1
    blur_size = 3
}


# Profile image
image {
   path = /home/xingyun/Downloads/khali.jpg
   position = 0, 5
   halign = center
   valign = center
   size = 100
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M %a %B %m")"
    font_size = 14
    font_family = JetBrainsMono Nerd Font Mono
    font_weight = 100
    position = 0, 140
    halign = center
    valign = center
}

# Username
label {
    monitor =
    text = $USER
    font_size = 10
    font_family = FiraCode Nerd Font
    font_weight = 800
    position = -10, 45
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 220, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.08)
    inner_color = rgba(255, 255, 255, 0.03)
    font_color = rgba(220, 220, 220, 1.0)
    fade_on_empty = true
    placeholder_text =
    shadow_passes = 0
    position = 0, -180
    halign = center
    valign = center
}
